version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/usr/share/nginx/html:ro"
            - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - app-network
        restart: always
        depends_on:
            - php
            - db
    php:
        image: nanoninja/php-fpm
        restart: always
        volumes:
            - "${PROJECT_ROOT}:/usr/share/nginx/html"
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
