version: "3.8"
services:
    web:
        image: nginx:latest
        #build:
            #context: .
            #dockerfile: Dockerfile.web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        restart: always
        #links:
            #- php-fpm
        depends_on: 
            php:
               condition: service_healthy
    php:
        image: php:8-fpm
        #restart: always
        volumes:
            - "${PROJECT_ROOT}:/var/www/html:ro"
    db:
        image: ivelin1936/bgapp-hw-db
        #build:
            #context: .
            #dockerfile: Dockerfile.db
        networks:
            - app-network
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
